# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'O:/studioTools/maya/python/tool/ptAlembic/exportCacheApp/exportUI.ui'
#
# Created: Mon Sep 28 00:50:57 2015
#      by: pyside-uic 0.2.14 running on PySide 1.2.0
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_AlembicExportWin(object):
    def setupUi(self, AlembicExportWin):
        AlembicExportWin.setObjectName("AlembicExportWin")
        AlembicExportWin.resize(648, 680)
        self.centralwidget = QtGui.QWidget(AlembicExportWin)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.frame_7 = QtGui.QFrame(self.centralwidget)
        self.frame_7.setFrameShape(QtGui.QFrame.Box)
        self.frame_7.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_16 = QtGui.QVBoxLayout(self.frame_7)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.project_label = QtGui.QLabel(self.frame_7)
        self.project_label.setObjectName("project_label")
        self.gridLayout.addWidget(self.project_label, 0, 1, 1, 1)
        self.label_8 = QtGui.QLabel(self.frame_7)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 2, 0, 1, 1)
        self.episode_label = QtGui.QLabel(self.frame_7)
        self.episode_label.setObjectName("episode_label")
        self.gridLayout.addWidget(self.episode_label, 1, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.frame_7)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 0, 1, 1)
        self.label_6 = QtGui.QLabel(self.frame_7)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 1, 0, 1, 1)
        self.sequence_label = QtGui.QLabel(self.frame_7)
        self.sequence_label.setObjectName("sequence_label")
        self.gridLayout.addWidget(self.sequence_label, 2, 1, 1, 1)
        self.label_10 = QtGui.QLabel(self.frame_7)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 3, 0, 1, 1)
        self.shot_label = QtGui.QLabel(self.frame_7)
        self.shot_label.setObjectName("shot_label")
        self.gridLayout.addWidget(self.shot_label, 3, 1, 1, 1)
        self.gridLayout.setColumnStretch(0, 1)
        self.gridLayout.setColumnStretch(1, 3)
        self.horizontalLayout_6.addLayout(self.gridLayout)
        self.logo2_label = QtGui.QLabel(self.frame_7)
        self.logo2_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.logo2_label.setObjectName("logo2_label")
        self.horizontalLayout_6.addWidget(self.logo2_label)
        self.logo_label = QtGui.QLabel(self.frame_7)
        self.logo_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.logo_label.setObjectName("logo_label")
        self.horizontalLayout_6.addWidget(self.logo_label)
        self.horizontalLayout_6.setStretch(0, 2)
        self.horizontalLayout_6.setStretch(1, 1)
        self.horizontalLayout_6.setStretch(2, 1)
        self.verticalLayout_16.addLayout(self.horizontalLayout_6)
        self.verticalLayout_9.addWidget(self.frame_7)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtGui.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtGui.QFrame.Box)
        self.frame.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame.setObjectName("frame")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.frame)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_2 = QtGui.QFrame(self.frame)
        self.frame_2.setFrameShape(QtGui.QFrame.Box)
        self.frame_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.frame_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label = QtGui.QLabel(self.frame_2)
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label)
        self.cache_listWidget = QtGui.QListWidget(self.frame_2)
        self.cache_listWidget.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.cache_listWidget.setObjectName("cache_listWidget")
        self.verticalLayout_4.addWidget(self.cache_listWidget)
        self.verticalLayout_3.addWidget(self.frame_2)
        self.frame_6 = QtGui.QFrame(self.frame)
        self.frame_6.setFrameShape(QtGui.QFrame.Box)
        self.frame_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_11 = QtGui.QVBoxLayout(self.frame_6)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_12 = QtGui.QLabel(self.frame_6)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout.addWidget(self.label_12)
        self.version_comboBox = QtGui.QComboBox(self.frame_6)
        self.version_comboBox.setObjectName("version_comboBox")
        self.horizontalLayout.addWidget(self.version_comboBox)
        self.increment_checkBox = QtGui.QCheckBox(self.frame_6)
        self.increment_checkBox.setObjectName("increment_checkBox")
        self.horizontalLayout.addWidget(self.increment_checkBox)
        self.horizontalLayout.setStretch(1, 2)
        self.verticalLayout_11.addLayout(self.horizontalLayout)
        self.label_3 = QtGui.QLabel(self.frame_6)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_11.addWidget(self.label_3)
        self.cache_lineEdit = QtGui.QLineEdit(self.frame_6)
        self.cache_lineEdit.setText("")
        self.cache_lineEdit.setObjectName("cache_lineEdit")
        self.verticalLayout_11.addWidget(self.cache_lineEdit)
        self.exportCacheAll_checkBox = QtGui.QCheckBox(self.frame_6)
        self.exportCacheAll_checkBox.setObjectName("exportCacheAll_checkBox")
        self.verticalLayout_11.addWidget(self.exportCacheAll_checkBox)
        self.exportCache_pushButton = QtGui.QPushButton(self.frame_6)
        self.exportCache_pushButton.setMinimumSize(QtCore.QSize(0, 30))
        self.exportCache_pushButton.setObjectName("exportCache_pushButton")
        self.verticalLayout_11.addWidget(self.exportCache_pushButton)
        self.verticalLayout_3.addWidget(self.frame_6)
        self.frame_4 = QtGui.QFrame(self.frame)
        self.frame_4.setFrameShape(QtGui.QFrame.Box)
        self.frame_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.frame_4)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_13 = QtGui.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_6.addWidget(self.label_13)
        self.camera_lineEdit = QtGui.QLineEdit(self.frame_4)
        self.camera_lineEdit.setText("")
        self.camera_lineEdit.setObjectName("camera_lineEdit")
        self.verticalLayout_6.addWidget(self.camera_lineEdit)
        self.exportCam_pushButton = QtGui.QPushButton(self.frame_4)
        self.exportCam_pushButton.setMinimumSize(QtCore.QSize(0, 30))
        self.exportCam_pushButton.setObjectName("exportCam_pushButton")
        self.verticalLayout_6.addWidget(self.exportCam_pushButton)
        self.verticalLayout_3.addWidget(self.frame_4)
        self.verticalLayout_2.addWidget(self.frame)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        spacerItem = QtGui.QSpacerItem(10, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem)
        self.cache_pushButton = QtGui.QPushButton(self.centralwidget)
        self.cache_pushButton.setMaximumSize(QtCore.QSize(40, 16777215))
        self.cache_pushButton.setObjectName("cache_pushButton")
        self.verticalLayout_7.addWidget(self.cache_pushButton)
        self.nonCache_pushButton = QtGui.QPushButton(self.centralwidget)
        self.nonCache_pushButton.setMaximumSize(QtCore.QSize(40, 16777215))
        self.nonCache_pushButton.setObjectName("nonCache_pushButton")
        self.verticalLayout_7.addWidget(self.nonCache_pushButton)
        self.refresh_pushButton = QtGui.QPushButton(self.centralwidget)
        self.refresh_pushButton.setMaximumSize(QtCore.QSize(40, 40))
        self.refresh_pushButton.setText("")
        self.refresh_pushButton.setObjectName("refresh_pushButton")
        self.verticalLayout_7.addWidget(self.refresh_pushButton)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem1)
        self.verticalLayout_7.setStretch(0, 1)
        self.verticalLayout_7.setStretch(1, 1)
        self.verticalLayout_7.setStretch(2, 1)
        self.verticalLayout_7.setStretch(3, 1)
        self.verticalLayout_7.setStretch(4, 4)
        self.horizontalLayout_2.addLayout(self.verticalLayout_7)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_3 = QtGui.QFrame(self.centralwidget)
        self.frame_3.setFrameShape(QtGui.QFrame.Box)
        self.frame_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.frame_3)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame_8 = QtGui.QFrame(self.frame_3)
        self.frame_8.setFrameShape(QtGui.QFrame.Box)
        self.frame_8.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.frame_8)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_2 = QtGui.QLabel(self.frame_8)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_10.addWidget(self.label_2)
        self.nonCache_listWidget = QtGui.QListWidget(self.frame_8)
        self.nonCache_listWidget.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.nonCache_listWidget.setObjectName("nonCache_listWidget")
        self.verticalLayout_10.addWidget(self.nonCache_listWidget)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.add_pushButton = QtGui.QPushButton(self.frame_8)
        self.add_pushButton.setObjectName("add_pushButton")
        self.horizontalLayout_5.addWidget(self.add_pushButton)
        self.remove_pushButton = QtGui.QPushButton(self.frame_8)
        self.remove_pushButton.setObjectName("remove_pushButton")
        self.horizontalLayout_5.addWidget(self.remove_pushButton)
        self.verticalLayout_10.addLayout(self.horizontalLayout_5)
        self.exportAll_checkBox = QtGui.QCheckBox(self.frame_8)
        self.exportAll_checkBox.setObjectName("exportAll_checkBox")
        self.verticalLayout_10.addWidget(self.exportAll_checkBox)
        self.exportNonCache_pushButton = QtGui.QPushButton(self.frame_8)
        self.exportNonCache_pushButton.setMinimumSize(QtCore.QSize(0, 30))
        self.exportNonCache_pushButton.setObjectName("exportNonCache_pushButton")
        self.verticalLayout_10.addWidget(self.exportNonCache_pushButton)
        self.verticalLayout_5.addWidget(self.frame_8)
        self.verticalLayout.addWidget(self.frame_3)
        self.frame_5 = QtGui.QFrame(self.centralwidget)
        self.frame_5.setFrameShape(QtGui.QFrame.Box)
        self.frame_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.frame_5)
        self.verticalLayout_8.setSpacing(2)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_14 = QtGui.QLabel(self.frame_5)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_8.addWidget(self.label_14)
        self.clear1_pushButton = QtGui.QPushButton(self.frame_5)
        self.clear1_pushButton.setMinimumSize(QtCore.QSize(0, 30))
        self.clear1_pushButton.setObjectName("clear1_pushButton")
        self.verticalLayout_8.addWidget(self.clear1_pushButton)
        self.deleteVersion_pushButton = QtGui.QPushButton(self.frame_5)
        self.deleteVersion_pushButton.setMinimumSize(QtCore.QSize(0, 30))
        self.deleteVersion_pushButton.setObjectName("deleteVersion_pushButton")
        self.verticalLayout_8.addWidget(self.deleteVersion_pushButton)
        self.clear2_pushButton = QtGui.QPushButton(self.frame_5)
        self.clear2_pushButton.setMinimumSize(QtCore.QSize(0, 30))
        self.clear2_pushButton.setObjectName("clear2_pushButton")
        self.verticalLayout_8.addWidget(self.clear2_pushButton)
        self.viewOutput_pushButton = QtGui.QPushButton(self.frame_5)
        self.viewOutput_pushButton.setMinimumSize(QtCore.QSize(0, 30))
        self.viewOutput_pushButton.setObjectName("viewOutput_pushButton")
        self.verticalLayout_8.addWidget(self.viewOutput_pushButton)
        self.verticalLayout.addWidget(self.frame_5)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout_2.setStretch(0, 8)
        self.horizontalLayout_2.setStretch(1, 1)
        self.horizontalLayout_2.setStretch(2, 7)
        self.verticalLayout_9.addLayout(self.horizontalLayout_2)
        AlembicExportWin.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(AlembicExportWin)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 648, 21))
        self.menubar.setObjectName("menubar")
        AlembicExportWin.setMenuBar(self.menubar)

        self.retranslateUi(AlembicExportWin)
        QtCore.QMetaObject.connectSlotsByName(AlembicExportWin)

    def retranslateUi(self, AlembicExportWin):
        AlembicExportWin.setWindowTitle(QtGui.QApplication.translate("AlembicExportWin", "PT Alembic Export v.1.0", None, QtGui.QApplication.UnicodeUTF8))
        self.project_label.setText(QtGui.QApplication.translate("AlembicExportWin", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("AlembicExportWin", "Sequence", None, QtGui.QApplication.UnicodeUTF8))
        self.episode_label.setText(QtGui.QApplication.translate("AlembicExportWin", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("AlembicExportWin", "Project", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("AlembicExportWin", "Episode", None, QtGui.QApplication.UnicodeUTF8))
        self.sequence_label.setText(QtGui.QApplication.translate("AlembicExportWin", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("AlembicExportWin", "Shot", None, QtGui.QApplication.UnicodeUTF8))
        self.shot_label.setText(QtGui.QApplication.translate("AlembicExportWin", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.logo2_label.setText(QtGui.QApplication.translate("AlembicExportWin", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.logo_label.setText(QtGui.QApplication.translate("AlembicExportWin", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("AlembicExportWin", "Cache List", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("AlembicExportWin", "Version", None, QtGui.QApplication.UnicodeUTF8))
        self.increment_checkBox.setText(QtGui.QApplication.translate("AlembicExportWin", "Increment Version", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("AlembicExportWin", "Cache Path", None, QtGui.QApplication.UnicodeUTF8))
        self.exportCacheAll_checkBox.setText(QtGui.QApplication.translate("AlembicExportWin", "Export All", None, QtGui.QApplication.UnicodeUTF8))
        self.exportCache_pushButton.setText(QtGui.QApplication.translate("AlembicExportWin", "Export Cache", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("AlembicExportWin", "Export Camera", None, QtGui.QApplication.UnicodeUTF8))
        self.exportCam_pushButton.setText(QtGui.QApplication.translate("AlembicExportWin", "Export Camera", None, QtGui.QApplication.UnicodeUTF8))
        self.cache_pushButton.setText(QtGui.QApplication.translate("AlembicExportWin", "<", None, QtGui.QApplication.UnicodeUTF8))
        self.nonCache_pushButton.setText(QtGui.QApplication.translate("AlembicExportWin", ">", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("AlembicExportWin", "Non Cache List", None, QtGui.QApplication.UnicodeUTF8))
        self.add_pushButton.setText(QtGui.QApplication.translate("AlembicExportWin", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.remove_pushButton.setText(QtGui.QApplication.translate("AlembicExportWin", "Remove", None, QtGui.QApplication.UnicodeUTF8))
        self.exportAll_checkBox.setText(QtGui.QApplication.translate("AlembicExportWin", "Export All", None, QtGui.QApplication.UnicodeUTF8))
        self.exportNonCache_pushButton.setText(QtGui.QApplication.translate("AlembicExportWin", "Export Non Cache", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("AlembicExportWin", "Setting", None, QtGui.QApplication.UnicodeUTF8))
        self.clear1_pushButton.setText(QtGui.QApplication.translate("AlembicExportWin", "Clear Selected Cache Data", None, QtGui.QApplication.UnicodeUTF8))
        self.deleteVersion_pushButton.setText(QtGui.QApplication.translate("AlembicExportWin", "Delete Unused Version", None, QtGui.QApplication.UnicodeUTF8))
        self.clear2_pushButton.setText(QtGui.QApplication.translate("AlembicExportWin", "Clear All Cache Data", None, QtGui.QApplication.UnicodeUTF8))
        self.viewOutput_pushButton.setText(QtGui.QApplication.translate("AlembicExportWin", "View Cache Output", None, QtGui.QApplication.UnicodeUTF8))

